### ISSUE TITLE
The player cannot circumcise sausages anymore

### ISSUE THREAD

**Issue by Daved27hundred** [Bubberstation/Bubberstation#1514]
## Issue Summary

Normally when you cut up a cooked sausage with a sharp object, you get a small menu that pops up asking if you want to cut it into pieces of salami or cut it into an "american sausage" with the tip missing. Haha. This wouldn't be a problem if not for the fact that this makes two very, very specific cooking recipes which use the american sausage impossible. Very urgent I know.
## Round ID:

round 4310

## Testmerges:

N/A

## Reproduction:

- Create sausage (meatball, 2 cutlets)
- Griddle sausage until it is cooked.
- Use a knife to cut the sausage, observe that you're no longer given the option of choice.

## Additional context:
pictured: section from a wiki that states the intended function
![image](https://github.com/Bubberstation/Bubberstation/assets/56202842/717c8423-f877-443a-9785-d6b404d95a59)
Also pictured: intended effect on TG
![image](https://github.com/Bubberstation/Bubberstation/assets/56202842/60faae55-b2ed-4f25-98de-682c0ed8f7d0)

**Comment by ReturnToZender** [comment]
what is this issue title

**Comment by IgiariValkyr** [comment]
Readd having to nip it with wirecutters, obviously

**Comment by Daved27hundred** [comment]
> Readd having to nip it with wirecutters, obviously

so THATS why burger told me to do that

**Comment by projectkepler-ru** [comment]
I don't understand this issue report

**Comment by Daved27hundred** [comment]
> I don't understand this issue report

see the last picture shown. That menu is supposed to show up when you try to cut a sausage, but it doesn't.

**Comment by Daved27hundred** [comment]
sorry, this was a late reply

**Comment by JagOfTroy** [comment]
So if I'm to understand this correctly, when you try to use the knife on the sausage, your trying to slice it into salami and that's the bug being reported? That it won't slice it like it should? Will attempt to repro later.

**Comment by JagOfTroy** [comment]
![Screenshot 2024-11-17 105335](https://github.com/user-attachments/assets/0523a440-fdad-4260-b0e0-b69d61f4eb4d)
![Screenshot 2024-11-17 105444](https://github.com/user-attachments/assets/de470596-3742-4f17-94ec-c09835328c8b)

This is indeed a bug. When you go to do the step with slice with knife, it automatically just goes to Salami. You'll see at the top, it just says 'Slice into Salami', it doesn't give the user the option to pick. 

I did verify there is at least one recipe in tg database(Budae-Jjigae) that is reliant(and quite complex) on the American Sausage so will start looking into the fix.

**Comment by JagOfTroy** [comment]
Looked directly at the American sausage itself in meatdish.dm, everything seems to be in place so not sure why the pop up, choice dialogue isn't happening like it should. Wondering if it has to do with the behavior of the knife itself.

**Comment by JagOfTroy** [comment]
![Screenshot 2024-11-17 113857](https://github.com/user-attachments/assets/8197bf5a-5484-4b3b-84b2-873caefd72bd)
![Screenshot 2024-11-17 113910](https://github.com/user-attachments/assets/f7d8bf16-3927-42b5-8cf9-b2d46c2505e1)
![Screenshot 2024-11-17 114123](https://github.com/user-attachments/assets/629538ae-a17c-4e1d-8e18-f3450d2c335e)
![Screenshot 2024-11-17 114145](https://github.com/user-attachments/assets/fa5cd744-bbce-44f3-b4d9-caf0967105d6)
![Screenshot 2024-11-17 114201](https://github.com/user-attachments/assets/4facc392-4c5b-4271-b19f-868068233273)
![Screenshot 2024-11-17 114212](https://github.com/user-attachments/assets/03d0b90a-c314-4e47-b2e7-eaef493f5527)

Tested this on standard TG database code, everything works like it should. So something is stopping the choice dialogue from popping up and it isn't being caused by TG but by something further down the line.
