### ISSUE TITLE
Wallmounted cryopods unable to be entered

### ISSUE THREAD

**Issue by unbinilium-120** [Bubberstation/Bubberstation#2040]
### Client Version:

515.1642

### Issue Summary:

When attempting to use a wallmounted cryopod it simply does not move the player inside causing the message pop up about entering the cryopod. due to this any situation where someone has to use a wallmounted cryopod they're unable to which is a problem for prisoners as they often only have wallmounted cryopods.

### Round ID:

5309

### Test Merge Information:

- [Public Logging Update](https://github.com/Bubberstation/Bubberstation/pull/1545)
- [GAS 2 - Part 2 - The Sequel, the worm, what you have been waiting for](https://github.com/Bubberstation/Bubberstation/pull/1471)
- [[TM ONLY] Reverts the TGUI stat panels](https://github.com/Bubberstation/Bubberstation/pull/1887)
- [The offstation cargo update (Ready for review)](https://github.com/Bubberstation/Bubberstation/pull/1764)
- [[TM ONLY] Unfucking disease outbreaks/transmission](https://github.com/Bubberstation/Bubberstation/pull/1919)
- [[PORT][TM ONLY] New Health Analyzer from TGMC](https://github.com/Bubberstation/Bubberstation/pull/1882)
- [Revenant Micro Patch](https://github.com/Bubberstation/Bubberstation/pull/1959)
- [Adds the xiarn and a related spawner, a admin only podperson variant](https://github.com/Bubberstation/Bubberstation/pull/1966)
- [Abductor machines no longer check for species when deciding if you can use it or not](https://github.com/Bubberstation/Bubberstation/pull/1964)
- [Bloodsucker power refactor](https://github.com/Bubberstation/Bubberstation/pull/1458)
- [Dollification Admin Smite](https://github.com/Bubberstation/Bubberstation/pull/1991)
- [Fleshmind (but using basic mob AI controllers)](https://github.com/Bubberstation/Bubberstation/pull/2007)
- [[Ready for Testmerge] Adds a new heretic path: Path of Exile](https://github.com/Bubberstation/Bubberstation/pull/2020)

### Reproduction Steps:

1. go to a wallmounted cryopod
2. attempt to enter it via dragging the character into the pod

**Comment by JagOfTroy** [comment]
Notes so far:
Can confirm this is an issue.
modular_skyrat/modules/cryosleep/code/cryopod.dm

First, sometimes the prisonpods don't connect to the cryogenic oversight for whatever reason so placing a local one will circumvent that since it looks for the closest one.
Having fixed that issue, when a player attempts to enter the wallmounted stasis pod, the animation flicks open and close but the player never enters. Your body never goes into stasis and the player object is still stuck standing outside of the pod.
--side note-- (Curious to see how it works possibly with other containers like the morgue)

The chat log will say 'Cletus Jerome starts climbing into the cryo pod.
If you ghost, log out or close your client now, your character will shortly be permanently removed from the round.
ADMIN LOG: [CologneEyes](Cletus Jerome) entered a stasis pod. ([JMP]

But none of this will have actually occurred. If you attempt to ghost, your body is just now free pickings and it never gets entered into the stasis system like it should if used like a normal pod. 

Attempts so far: I've tried several things. My brain hurts. Will revisit this again since the solution for this bug interests me.
![Screenshot 2024-11-15 203131](https://github.com/user-attachments/assets/63d7119e-425f-45bd-b9eb-30764ade5c14)
![Screenshot 2024-11-15 203218](https://github.com/user-attachments/assets/a905a046-e7ec-4083-aedd-cd8b81762d48)
