### ISSUE TITLE
Dauntless Borgs Should Have The Syndicate Faction

### ISSUE THREAD

**Issue by Tupinambis** [Bubberstation/Bubberstation#599]
At the moment, any borgs built on the dauntless are automatically targeted by the facility turrets and will be denied access by airlocks (though they can just remotely open them)

Perhaps the dauntless should spawn with borg mods that give them syndie faction? I assume that'd be the easiest solution.

While I understand there may be arguments against it, I'd also appreciate being able to choose syndicate modules or get emag mods for flavor. The dauntless SHOULDN'T be fucking with the crew without opfor so this SHOULDN'T really be a significant balance problem. (should probably be limited with boards so the dauntless crew don't decide to make 10 syndieborgs or something silly like that)

**Comment by StrangeWeirdKitten** [comment]
The airlocks are mapped specifically to have the AI wire cut, so this is not a faction thing. You can disable borg targetting by the turrets since that is a faction thing. I made the conscious decision not to let Dauntless have access to an emag, illegal board mod (roundstart), and a syndicate cyborg module. Regarding Dauntless, my project with it is done. I am no longer closely monitoring everyone who plays it and I am not going to give players access to stuff that I'm not willing to accept worst-case scenario.
