### ISSUE TITLE
[BOUNTY] Port 'vocal barks' from Goonstation/Daedalus Dock

### ISSUE THREAD

**Issue by shayoki** [Bubberstation/Bubberstation#688]
## What

It may not be a direct port, but in essence,
This bounty is asking for a chosen sound effect to play when another character/mob speaks.
Players should be able to pick from their character preferences which voice a character will talk with.

Preferably only heard if someone can be seen talking or wall-pierced if yelled.
Can not be heard if a character isn't seen talking or whispered.

This will be is a toggleable option in game preferences.
Along with an option for 'None' as a voice option.

<details>
<summary><h4>What else?</h4></summary>
Some preferred Additions to this that aren't required for the bounty:
<br>
<b>·Make this modular.</b><br>
<b>·Make it simple for more voices to be added.</b><br>
<b>·Muffle voices if mob has a spacesuit on.</b>
</details>

## Why

Because spessmen have voices. _realism_.
This will aid when grabbing someone's attention with a small sound cue along with the visual cue.
Quality of life improvements.

### $60 USD.
$60 from Gavla
Contact Gavla on Discord if you'd like to chip in.

Amount will be paid in full to the contributor via PayPal or other preferred option. (i.e. Ko-fi, CashApp)
It is up to the main contributor of the PR to split the funds in the case there is more than one contributor for the feature. 

## Resources
(more to come later)
~~https://github.com/goonstation/goonstation/tree/master/sound/misc/talk (Voices)~~ (Use these for example purposes in your PR. I'd advise to keep the PR in a draft until new sounds are made)
https://github.com/DaedalusDock/daedalusdock/pull/16 (Daedalus voice pull)

### Yeah.
And it's here https://github.com/Bubberstation/Bubberstation/pull/862
Though it is a draft, help is appreciated. Wanna work on it? Comment or let me know on Discord.

**Comment by Kapu1178** [comment]
Every Daedalus Dock mention finds it's way to me
![artworks-cYInJFs7iFhj2ost-azODGQ-t500x500-2943886099](https://github.com/Bubberstation/Bubberstation/assets/75460809/92012ab7-2e0c-4fa9-8cf2-ad1a753274d4)


Anyway doing this the way described wouldn't really be a good idea, since the way to do it very cheaply is to tie it directly into how mobs hear eachother talk. 

Additionally, the sound files violate the contributor guidelines of Bubberstation which states assets will only be accepted as CC-BY-SA. Goon's sounds are under CC-BY-NC-SA.

**Comment by IgiariValkyr** [comment]
I'd rather have vocal barks than this "Character Voice" thing

**Comment by RaShCat** [comment]
60$? Lol.
