### ISSUE TITLE
Contractor TC

### ISSUE THREAD

**Issue by StrangeWeirdKitten** [Bubberstation/Bubberstation#823]
Discuss contractor TC feedback here for #807

**Comment by projectkepler-ru** [comment]
Should probably close that PR and remove drifting contractor then keep it as a crew kit. They've always been a pain in th side to balance

**Comment by The-Sun-In-Splendour** [comment]
Either give them 13TC back or make them guaranteed to get a doormag upon spawn. Spawning as contractor is literally just a gamble right now. You could get good items which are awesome but you get 0 way to get into places, _**and getting into places is a 75% of contractor gameplay.**_ You're not going to get far as a contractor if you can only slowly hack with wirecutters into places.

**Comment by projectkepler-ru** [comment]
I'm still under the opinion of removing drifting contractor entirely in favour of having it as a traitor kit as that the provision to it is entirely your responsibility

**Comment by radarseas** [comment]
I'd change the baton holster to something like a recall mod that ninja gets with a long-cooldown, ditch this weird modularity the contract baton has but never uses because of the radio jammer existing so you can't beat people with it and lock the contract-baton from working by any _non-contractors_ and have drifters stay the higher-risk midround non-crew with say 10TC they were always supposed to be.

Have the contract-kit return from OPFOR as a 25TC _all-in-high-stakes-high-reward_ traitor option without the modsuit, move the modsuit to replace the magnetic thingy **_that cargo can buy for some godforsaken reasoning for a couple of credits_** in their rep menu and have midrounds get 2 rep, traitor kit tots get 1 rep per contract.

This'll also encourage infils to not go contractor since they'll get poorer rewards out of it and have to do more for the mod... when they already have one off the bat.

==============================================================================

Drifters have their place, I think a mix of non-crew and crew syndies is good since we got statics to fill both. Its nice to see characters exclusively from the Syndicate time to time where they make the most sense and its also a nice jump in threat where rounds suffer from a lack of loud antagonising without ninja's nuke-it-all with doorjacks and emps.

Afterall, I think its good to have our own blend of humanoid antagonists from the Syndicate that aren't present just to nuke everything to hell and can focus more on their factional gimmic without the ties of being crew.
